name: quality-gate

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  style-check:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install

      - name: Run a one-line script
        run: npm run lint
